GO

/****** Object:  DatabaseRole [GP_REPORTESADICIONALES]    Script Date: 25/09/2015 17:09:05 ******/
IF DATABASE_PRINCIPAL_ID('GP_REPORTESADICIONALES') IS NULL
 CREATE ROLE [GP_REPORTESADICIONALES]
GO


