GO

/****** Object:  DatabaseRole [TII_CTA_CTE_PROVEEDOR]    Script Date: 25/09/2015 17:09:05 ******/
IF DATABASE_PRINCIPAL_ID('TII_CTA_CTE_PROVEEDOR') IS NULL
 CREATE ROLE [TII_CTA_CTE_PROVEEDOR]
GO


